# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: Terraform Deploy with Snyk Security Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Analyse de sécurité avec Snyk sur runner GitHub
  security-scan:
    runs-on: ubuntu-latest  # Runner hébergé par GitHub
    outputs:
      scan-result: ${{ steps.check-results.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snyk IaC scan
        id: snyk-scan
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
        continue-on-error: true

      - name: Check Snyk scan results
        id: check-results
        run: |
          if [ "${{ steps.snyk-scan.outcome }}" == "failure" ]; then
            echo "⛔ Vulnérabilités détectées par Snyk - même de niveau 'low'"
            echo "❌ Déploiement Terraform sera bloqué pour des raisons de sécurité"
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "✅ Aucune vulnérabilité détectée. Déploiement Terraform autorisé."
            echo "result=success" >> $GITHUB_OUTPUT
          fi

      - name: Generate Snyk Report
        if: steps.snyk-scan.outcome == 'failure'
        run: |
          echo "### Rapport de vulnérabilités Snyk 🔍" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Des vulnérabilités ont été détectées dans votre infrastructure. Le déploiement sera bloqué." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Consultez les logs de l'étape 'Run Snyk IaC scan' pour plus de détails." >> $GITHUB_STEP_SUMMARY

  # Job 2: Déploiement Terraform sur runner auto-hébergé
  terraform-deploy:
    needs: security-scan  # Attend que le job security-scan soit terminé
    if: needs.security-scan.outputs.scan-result == 'success'  # Exécute uniquement si le scan est réussi
    runs-on: self-hosted  # Utilise votre runner auto-hébergé
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optionnel si Terraform est déjà installé sur votre runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Spécifiez la version souhaitée

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: tf-apply  
        run: terraform apply -auto-approve tfplan

  # Job 3: Notification en cas d'échec de sécurité
  notification-failure:
    needs: security-scan
    if: needs.security-scan.outputs.scan-result == 'failure'
    runs-on: ubuntu-latest  # Peut être n'importe quel runner
    steps:
      - name: Notification d'échec
        run: |
          echo "Le déploiement a été bloqué car Snyk a détecté des vulnérabilités."
          echo "Veuillez consulter les résultats de l'analyse pour plus de détails."
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.office365.com
            server_port: 587
            secure: starttls  # MODIFICATION IMPORTANTE ICI
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: "⚠️ [GitHub Actions] Vulnérabilités détectées dans l'Infrastructure"
            html_body: |
              <h1>Alerte de sécurité</h1>
              <p>Des vulnérabilités ont été détectées.</p>
            to: ${{ github.event.pusher.email }}
            from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
      # Vous pourriez ajouter ici des actions pour envoyer des notifications (Slack, email, etc.)
      # - name: Send Slack notification
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     slack-message: "⛔ Déploiement Terraform bloqué - Vulnérabilités détectées"
      #     channel-id: "C123456"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}



